Added Feedly recipe
getferdi/recipes pull request #254
Opened 2020-08-07 04:53 UTC by kastnerp

2020-09-19 18:23 UTC, kytwb requested changes
I see there is a Franz recipe available at https://github.com/alphamyd/meetfranz-recipe-feedly, have you tried it?

2020-09-19 18:23 UTC, kytwb commented on uncompressed/feedly/webview.js
> +  const createModal = () => {
I don't understand why a modal is being created.

2020-09-19 18:43 UTC, kytwb commented on uncompressed/feedly/webview.js
> +  const getMessages = () => Franz.setBadge(updates);
I don't use Feedly so I am not sure if it is really needed to override `window.alert` with this modal logic. Isn't it possible to get the notifications count thanks to a call to `document.querySelector` like in https://github.com/alphamyd/meetfranz-recipe-feedly/blob/6b5d39962d516dd4b6cfdd74526d310f6cf321a5/webview.js#L4?

2020-09-19 18:46 UTC, kastnerp commented
You are right, I had not tested the other one.

2020-09-19 19:07 UTC, kytwb commented on uncompressed/feedly/feedly.css
> +}
```suggestion
```

2020-09-19 19:09 UTC, merged

2020-09-19 19:10 UTC, kytwb commented
@kastnerp thank you for your contribution!

I merged despite the failing build as part of the refactor taking place in #292.

2020-09-20 00:59 UTC, kytwb commented
Fixes https://github.com/getferdi/recipes/issues/233.