Fix slack SSO with Google
getferdi/recipes pull request #599
Opened 2021-07-19 13:51 UTC by sad270

fix issue: https://github.com/getferdi/ferdi/issues/1350

2021-07-19 13:55 UTC, vraravam requested changes

2021-07-19 13:55 UTC, vraravam commented on recipes/slack/index.js
> +                        'user-agent': window.navigator.userAgent.replace(/(Ferdi|Electron)\/\S+( \([^)]+\))?/g, "").trim(),
@sad270 - this line should no longer be needed.  The user now has the ability to override the `user-agent` from within the preferences/settings screen in Ferdi. Please confirm.

2021-07-19 13:55 UTC, vraravam commented on recipes/slack/index.js
> +                        'user-agent': window.navigator.userAgent.replace(/(Ferdi|Electron)\/\S+( \([^)]+\))?/g, "").trim(),
I am logging into slack via an okta-based SSO - and I do not need this "fix"

2021-07-19 14:23 UTC, sad270 commented on recipes/slack/index.js
> +                        'user-agent': window.navigator.userAgent.replace(/(Ferdi|Electron)\/\S+( \([^)]+\))?/g, "").trim(),
Hello,
I already try to change the UA from the service configuration but it's doesn't work
I have a slack with Google Sign in only, and my Google Account have 2FA, the login fail after the 2FA authentification (when I click on "Yes" on my Phone)
I explain all here https://github.com/getferdi/ferdi/issues/1350#issuecomment-851336929

I try:
* Override UA from the service config without changing the `index.js`
* Override UA from the service config and with only the `requestFilters` (line 12) in the `index.js`
* Only `requestFilters` (line 12) in the `index.js` with default UA
* Only change `modifyRequestHeaders` UA (line 9) without the `requestFilters` (line 12)

It doesn't work all of them failed after the 2FA

Note: In my test, I override UA in service config with: `Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko)1.1 Chrome/91.0.4472.77 Safari/537.36`

2021-07-19 14:26 UTC, sad270 commented
I use the last Nightly 😎

```
Version: 5.6.0-nightly.88
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
Platform: macOS Catalina
Arch: x64
Build date: Sun Jul 18 2021 04:08:58 GMT+0200 (Central European Summer Time)
Git SHA: 8b87a1e2
Git branch: nightly
```

2021-07-20 15:29 UTC, JustoHermano commented on recipes/slack/index.js
> +                        'user-agent': window.navigator.userAgent.replace(/(Ferdi|Electron)\/\S+( \([^)]+\))?/g, "").trim(),
My company is using slack login via okta aswell and login is currently failing aswell even with the user agent above

2021-09-21 10:56 UTC, vraravam commented
@sad270 - please review this PR, fix it and resubmit or we can close it?

2021-09-22 12:06 UTC, sad270 commented
Yes, sorry i forgot this. I will work on this PR this weekend.

2021-09-26 16:35 UTC, sad270 commented
This can be closed since https://github.com/getferdi/ferdi/pull/1991 is merged

2021-09-27 02:26 UTC, closed without merging