build: migrate from npm to pnpm
getferdi/recipes pull request #603
Opened 2021-08-08 14:50 UTC by mhatvan

- remove package-lock.json
- add pnpm-lock.yaml

Precondition to finish PR: https://github.com/getferdi/ferdi/pull/1714

2021-08-08 15:23 UTC, vraravam requested changes

2021-08-08 15:23 UTC, vraravam commented on scripts/create.js
> +const fs = require("fs-extra");
Didn't we decide to use single quotes all over?

2021-08-08 15:45 UTC, mhatvan commented on scripts/create.js
> +const fs = require("fs-extra");
You are correct, this is the default setting of prettier.

We don't have a `.prettierrc.js` config in the recipes project, therefore this happened.

I will add one.

2021-08-08 15:47 UTC, mhatvan commented on scripts/create.js
> +const fs = require("fs-extra");
Done.

2021-08-23 06:51 UTC, vraravam approved these changes

2021-09-08 08:33 UTC, merged