chore: fix blank recipe icons
getferdi/recipes pull request #611
Opened 2021-08-18 06:50 UTC by mhatvan

- fixed aws workmail, google contacts, kimai cloud, line.me, paymoapp, superhuman, ticktick icons
- fixed plan icon aspect ratio

## findings for follow up PRs

- hackmd and zimbra don't have a svg in ferdi, didn'tind one to use
- glowing bear shows up twice but exists correctly only once in recipes?

2021-08-18 06:54 UTC, vraravam commented
> glowing bear shows up twice but exists correctly only once in recipes?

This might be a bug - and will have to have a validation check also introduced while running `npm run package`

> what to do about duplicate services like Outlook?

I think, since we have introduced the aliases, we can now collapse them into one? What do you think?

Note: Please do these as a new PR - not within this same one.

2021-08-18 06:58 UTC, mhatvan commented
Will open an issue for glowing bear.

Not sure how this works, wouldn't the users' configuration get purged if we collapse the service and the recipe is not found anymore?

2021-08-18 07:00 UTC, vraravam requested changes

2021-08-18 07:00 UTC, vraravam commented on recipes/kimai-cloud/package.json
> +  "id": "kimai-cloud",
Also need a version bump if we proceed with the name change

2021-08-18 07:07 UTC, vraravam commented
> Not sure how this works, wouldn't the users' configuration get purged if we collapse the service and the recipe is not found anymore?

Yes - and wearing a user's hat, I would not like Ferdi if it did that!

2021-08-19 06:15 UTC, mhatvan commented on recipes/aws-workmail/package.json
>    "version": "1.0.5",
There is only a check if there is an id field. What would that validation look like? Can't think of a good way to check if anything in package xyz got changed and needs id higher than current one.

2021-08-19 06:21 UTC, mhatvan commented on recipes/googlecontacts/package.json
> +  "id": "googlecontacts",
I created a discussion here: https://github.com/getferdi/ferdi/discussions/1814

2021-08-19 06:33 UTC, vraravam commented on recipes/aws-workmail/package.json
>    "version": "1.0.5",
You can mimic the check that I have implemented based on `git diff` for this.

2021-09-12 15:13 UTC, vraravam commented on recipes/googlecontacts/package.json
> +  "id": "googlecontacts",
i don't think we can **change** an `id` - since the recipe has already been "released" and folks might be using it with that `id`

2021-09-12 15:13 UTC, vraravam commented on recipes/aws-workmail/package.json
>    "version": "1.0.5",
i don't think we can **change** an `id` - since the recipe has already been "released" and folks might be using it with that `id`

2021-09-12 15:19 UTC, vraravam commented
>  what to do about duplicate services like Outlook?
A few weeks ago, I had merged the outlook-related services into 1: `office365 - owa`.

Similarly, I had done the same merge from `github_enterprise` into `github` earlier today

2021-09-12 15:20 UTC, vraravam commented on recipes/aws-workmail/package.json
> +  "id": "aws-workmail",
i don't think we can **change** an `id` - since the recipe has already been "released" and folks might be using it with that `id`

2021-09-12 15:22 UTC, vraravam requested changes

2021-09-12 15:22 UTC, vraravam commented on recipes/kimai-cloud/package.json
> +  "id": "kimai-cloud",
i don't think we can **change** an `id` - since the recipe has already been "released" and folks might be using it with that `id`

2021-09-12 15:22 UTC, vraravam commented on recipes/line.me/package.json
> +  "id": "line.me",
i don't think we can **change** an `id` - since the recipe has already been "released" and folks might be using it with that `id`

2021-09-12 15:22 UTC, vraravam commented on recipes/paymoapp/package.json
> +  "id": "paymoapp",
i don't think we can **change** an `id` - since the recipe has already been "released" and folks might be using it with that `id`

2021-09-12 15:22 UTC, vraravam commented on recipes/plan/package.json
> +  "version": "1.0.3",
If we don't have any other change, then lets avoid the version bump

2021-09-12 15:22 UTC, vraravam commented on recipes/superhuman-email/package.json
> +  "id": "superhuman-email",
i don't think we can **change** an `id` - since the recipe has already been "released" and folks might be using it with that `id`

2021-09-12 15:22 UTC, vraravam commented on recipes/ticktick/package.json
> +  "id": "ticktick",
i don't think we can **change** an `id` - since the recipe has already been "released" and folks might be using it with that `id`

2021-09-12 15:48 UTC, mhatvan commented
Closing since we would introduce breaking changes for the user. We will need to do this in a smarter way, e.g. to modify blank icon paths hosted on jsdelivr to fix this.

2021-09-12 15:48 UTC, closed without merging