New recipe: scribens
getferdi/recipes pull request #651
Opened 2021-08-27 21:13 UTC by oda-alexandre

## Adding new recipe

Service: [Scribens]

URL: [https://scribens.{teamId}]

Service ID: [scribens]

### Terminal output

```bash
[npm run package

> ferdi-recipes@1.0.0 package
> node scripts/package.js

✅ Successfully packaged and added 182 recipes (0 unsuccessful recipes)]
```

### Additional information

- [x] I am the original creator of this package
- [x] I have run the `npm run package` and verified that there are no validation errors reported for this package
- [x] My recipe has been tested to work inside Ferdi

2021-08-27 23:23 UTC, vraravam requested changes

2021-08-27 23:23 UTC, vraravam commented on recipes/scribens/webview.js
> +//   Ferdi.injectCSS(_path.default.join(__dirname, 'service.css'));
Please uncomment the outer shell (as auto-generated) so that the user can override the css alone by editing the `service.css` file.

2021-08-27 23:23 UTC, vraravam commented on recipes/scribens/webview.js
> +//   // const getMessages = function getMessages() {
Are there unread count badges that are pertinent to this service?

2021-08-28 11:43 UTC, oda-alexandre commented on recipes/scribens/webview.js
> +//   // const getMessages = function getMessages() {
No count badges to this service !

2021-08-28 11:47 UTC, vraravam approved these changes

2021-08-28 11:47 UTC, vraravam commented on recipes/scribens/webview.js
> +//   // const getMessages = function getMessages() {
thanks - but, the `service.css` can still be uncommented.

2021-08-28 11:47 UTC, merged