Fix images opening in browser instead of in Discord
getferdi/recipes pull request #712
Opened 2021-09-15 16:25 UTC by briankendall

fe613088a813394760ca27afeee554cfa7290d67 introduced a bug where clicking an image in Discord would cause it to open in the default browser rather than displaying full size within Discord itself. This may potentially fix other bugs as the recipe was programmed to open any link in a browser rather than letting Discord itself handle it. Hopefully it doesn't introduce any new bugs as well.

2021-09-15 17:01 UTC, vraravam requested changes
thanks @briankendall . Please bump up the `version` in the `package.json` of the specific recipe , and then run the `npm run package` task. This will ensure the changes are valid - and will auto-generate the changes to the `all.json` file. All these are needed for the PR to be approved.

2021-09-15 17:08 UTC, briankendall commented
Okay, done. Let me know if there's anything else I should do.

2021-09-15 17:10 UTC, vraravam approved these changes

2021-09-15 17:11 UTC, merged

2021-09-15 17:12 UTC, vraravam commented
This will appear in the next nightly @briankendall - thanks for your contribution!  🎉🎉🎉🎉

2021-09-15 17:43 UTC, mhatvan commented
Great work, thanks @briankendall !!

2021-11-06 15:23 UTC, m-vlad commented
Thanks, i was able to do the changes in this pull request manually on my side since I can't update to nightly and it worked.

2021-12-23 16:49 UTC, kytwb commented
@all-contributors please add @briankendall for code