Add Confluence recipe
getferdi/recipes pull request #758
Opened 2021-10-31 15:25 UTC by vantezzen

This PR adds a recipe for [Confluence](https://www.atlassian.com/de/software/confluence).

Closes #82

2021-10-31 19:20 UTC, mhatvan commented on recipes/confluence/index.js
> +module.exports = Ferdi => class confluence extends Ferdi {};
`class` name is always title case, e.g. Confluence.

But you can also simplify to: `module.exports = Ferdi => Ferdi;`

2021-10-31 19:20 UTC, mhatvan commented on recipes/confluence/webview.js
> +    Ferdi.setBadge(unreadMessageCountElement ? Number(unreadMessageCountElement.textContent) : 0, 0);
Hard to read, I would move `unreadMessageCountElement ? Number(unreadMessageCountElement.textContent) : 0` into separate variable declaration.

2021-10-31 19:24 UTC, vantezzen commented on recipes/confluence/index.js
> +module.exports = Ferdi => class confluence extends Ferdi {};
Interesting, might need to update the automatic creator script there. The script generates the names like this - see existing recipes like https://github.com/getferdi/recipes/pull/720/files.

Thank you for the feedback, I will update the class declaration there

2021-10-31 20:17 UTC, mhatvan approved these changes

2021-11-01 00:01 UTC, vraravam requested changes

2021-11-01 00:01 UTC, vraravam commented on recipes/confluence/webview.js
> +    const unreadMessagesCount = unreadMessageCountElement ? Number(unreadMessageCountElement.textContent) : 0;
Please use `Ferdi.safeParseInt` - which can remove line 8

2021-11-01 00:01 UTC, vraravam commented on recipes/confluence/webview.js
> +  Ferdi.injectCSS(_path.default.join(__dirname, 'service.css'));
If the `service.css` is empty, why include it?

2021-11-01 01:08 UTC, vraravam commented on recipes/confluence/README.md
> +# Confluence for Ferdi
This file also seems redundant. Please remove

2021-11-01 06:53 UTC, vantezzen commented on recipes/confluence/webview.js
> +  Ferdi.injectCSS(_path.default.join(__dirname, 'service.css'));
This file and the Readme is generated by the creator script. As you also seem to include them (https://github.com/getferdi/recipes/pull/720/files) I thought they should remain. Might need to update the creator script if this is not wanted, I will remove them from this PR

2021-11-01 09:46 UTC, vraravam commented on recipes/confluence/webview.js
> +  Ferdi.injectCSS(_path.default.join(__dirname, 'service.css'));
Thanks for catching that - I have now fixed the unnecessary `service.css` in those recipes that do not use it. Please rebase from `master` - and rerun the `pnpm run package` command against your PR branch.

2021-11-01 09:47 UTC, vraravam commented on recipes/confluence/README.md
> +# Confluence for Ferdi
This also has been removed from the creation script.

2021-11-01 09:47 UTC, vraravam commented
Once the PR is completed, please *squash* and merge/rebase into the `master` branch - each PR (for this repo) needs to have only a single logical commit.

2021-11-01 22:22 UTC, vraravam approved these changes

2021-11-01 22:23 UTC, merged