Add recipe for Chatwoot
getferdi/recipes pull request #760
Opened 2021-11-04 14:46 UTC by maximeMD

This PR adds a recipe for [Chatwoot](https://www.chatwoot.com/).

2021-11-04 14:56 UTC, vraravam requested changes

2021-11-04 14:56 UTC, vraravam commented on recipes/chatwoot/webview.js
> +      Number.parseInt(unreadBadgesArray.textContent),
Please use `Ferdi.safeParseInt` instead of `Number.parseInt`

2021-11-04 14:56 UTC, vraravam commented on recipes/chatwoot/webview.js
> +    const unreadMessagesCount = unreadBadgesValues.reduce((a, b) => a + b);
Rather than using `map` followed by `reduce`, you can use `reduce` directly and collect the sum.

2021-11-04 15:41 UTC, maximeMD commented
I just pushed some changes, could you please check this again ? 😺

2021-11-04 17:03 UTC, vraravam commented on recipes/chatwoot/webview.js
> +    const unreadBadges = document.querySelectorAll("span.unread");
We prefer single quotes. But, i'll approve this PR as is

2021-11-04 17:04 UTC, vraravam approved these changes

2021-11-04 17:05 UTC, merged

2021-12-23 16:50 UTC, kytwb commented
@all-contributors please add @maximeMD for code