Toggl recipe: Display 'unread' badge when a timer is running
getferdi/recipes pull request #767
Opened 2021-11-20 17:30 UTC by n-st

This PR adds an "unread" badge to the Toggl service whenever a timer is running.

It uses Toggl's own JavaScript interface — this lets us get away without searching for hardcoded CSS classes in the DOM, but requires passing information between the service context (where the `toggl` object is available) and the Electron context (where the `ferdi` object is available).
Currently, the only way I've found to do that is with `Ferdi.injectJSUnsafe` — and since the `ferdi` object inside the unsafe JS doesn't offer the usual `loop()` function, I have to reinject my JS on every loop…
Is there a more efficient way to do this?

Side note: The Toggl JS interface also exposes the name of the currently running timer, so we could `ferdi.setDialogTitle`, but that doesn't seem to be available in my Ferdi 5.6.1, either…

2021-11-20 19:58 UTC, vraravam requested changes

2021-11-20 19:58 UTC, vraravam commented on recipes/toggl/webview.js
> +    const path = require('path');
Please use the pattern found in other recipes where the `webview-unsafe.js` is injected.
Look for `_interopRequireDefault` for eg in the `googlecalendar` recipe

2021-11-20 20:30 UTC, n-st commented on recipes/toggl/webview.js
> +    const path = require('path');
Done, thank you for the feedback.

2021-11-20 20:48 UTC, vraravam approved these changes
lgtm

2021-11-20 20:49 UTC, vraravam commented
btw - ferdi is at v5.6.3 right now. You might want to upgrade.

2021-11-20 20:49 UTC, merged

2021-11-20 21:00 UTC, n-st commented
@vraravam Does it impact performance or memory usage to inject the JS file so often? Is there a more efficient way (since I'm only doing it so I can use ferdi.loop())?

2021-11-20 21:12 UTC, vraravam commented
Not sure - lets wait and watch. Please try out the next nightly and keep an eye out on this factor?

2021-11-23 13:25 UTC, simonszu commented
This commit is breaking the linter which is triggered in the pre-commit hook: 

```
simonszu@maenas:~/recipes/recipes$ git commit -m "Added recipe for circuit"

> ferdi-recipes@1.0.0 lint /home/simonszu/recipes
> eslint . --fix


/home/simonszu/recipes/recipes/toggl/webview-unsafe.js
  2:5   error  'ferdi' is not defined  no-undef
  2:27  error  'ferdi' is not defined  no-undef
  7:9   error  'ferdi' is not defined  no-undef
  9:9   error  'ferdi' is not defined  no-undef

✖ 4 problems (4 errors, 0 warnings)

 ELIFECYCLE  Command failed with exit code 1.
husky - pre-commit hook exited with code 1 (error)
```

2021-11-25 21:56 UTC, n-st commented
@simonszu Would it satisfy the linter to use `window.ferdi` there?

2021-11-25 22:07 UTC, simonszu commented
I think this was already fixed with 
https://github.com/getferdi/recipes/commit/b88f3a009471711299a5878fdadf6d197b505f27

2021-12-23 16:42 UTC, kytwb commented
@all-contributors please add @n-st for code