XMPP recipe
getferdi/recipes pull request #768
Opened 2021-11-21 14:36 UTC by Aman9das

This basically compiles 2 different projects.. kindly review the PR

2021-11-21 15:01 UTC, vraravam requested changes
Please remove the `png` file from the PR.

2021-11-21 15:01 UTC, vraravam commented on recipes/xmpp/webview.js
> +            direct += parseInt(indicator.innerText, 10)
Please use `Ferdi.safeParseInt` for parsing text into numbers.

2021-11-21 15:01 UTC, vraravam commented on recipes/xmpp/webview.js
> +        Franz.setBadge(direct, indirect);
If `indirect` is always zero, you can remove the references.

2021-11-22 01:27 UTC, Aman9das commented
Thanks a lot! Hopefully this is ok now :)

2021-11-22 01:28 UTC, vraravam commented on recipes/xmpp/package.json
> +    "id": "xmpp",
Please adhere to the formatting of 2 spaces, no tabs

2021-11-22 01:29 UTC, vraravam requested changes

2021-11-22 01:29 UTC, vraravam commented on recipes/xmpp/webview.js
> +        let indirect = 0;
Please remove the unused variable.

2021-11-22 01:31 UTC, vraravam requested changes

2021-11-22 01:31 UTC, vraravam commented on recipes/xmpp/webview.js
> +            direct += Ferdi.safeParseInt(indicator.innerText, 10)
There's no 2nd argument for `Ferdi.safeParseInt`

2021-11-22 01:39 UTC, vraravam commented
@Aman9das - please follow the instructions in the README while contributing a new recipe. There's a step related to running the `pnpm` command. This would have modified the `all.json` file - which needs to be included in the PR. I don't see that change. Please follow the steps and add all the changed files.

2021-11-22 12:55 UTC, vraravam requested changes

2021-11-22 12:55 UTC, vraravam commented on recipes/toggl/webview-unsafe.js
> -// only try to update badge once Ferdi API has finished loading
Why are you deleting code for a recipe that isn't related to this PR?

2021-11-22 12:55 UTC, vraravam commented on recipes/xmpp/webview.js
> +        // let indirect = 0; //will be used in a future verios
We dont need this for now - please remove. Its just noise.

2021-11-22 12:59 UTC, vraravam commented
Please rebase from the `master` branch of the upstream - so that the issues with the `toggl` recipe are fixed.

2021-11-23 07:39 UTC, Aman9das commented on recipes/toggl/webview-unsafe.js
> -// only try to update badge once Ferdi API has finished loading
OH i forgot to tell, theres an issue with that recipe that is preventing git commit..

2021-11-23 07:40 UTC, Aman9das commented on recipes/xmpp/webview.js
> +        // let indirect = 0; //will be used in a future verios
Documentation, it won't afffect performance, please just let it be. Documentation in any form is helpful for the next person down the line

2021-11-23 07:41 UTC, Aman9das commented
Please create some other branch to rebase to.. I will rebase.

2021-11-23 08:23 UTC, vraravam commented
> Please create some other branch to rebase to.. I will rebase.

Your PR should have been against a different branch in your fork. Please see the published docs from Github.

The CI process has not thrown any error with the `toggl` recipe. Please disregard anything that might show up on your local machine.

2021-11-23 08:26 UTC, vraravam commented on recipes/xmpp/webview.js
> +        // let indirect = 0; //will be used in a future verios
Though I agree in general, but, this line (imo) is not "documentation". I can accept this for now.

2021-11-23 08:26 UTC, vraravam commented on recipes/toggl/webview-unsafe.js
> -// only try to update badge once Ferdi API has finished loading
Please undo this change - cannot be compromised for this PR.

2021-11-23 08:27 UTC, vraravam requested changes
The changes to the `toggl` recipe should be undone.

2021-11-23 12:48 UTC, Aman9das commented
The toggl webview-unsafe 'ferdi undefined' error is not letting me commit. the data is present in the pr, kindly try to implement the recipe properly on own device if possible.

Closing the pr as can't satisfy the scripts

2021-11-23 16:17 UTC, vraravam commented
Closing this PR - since the code has been merged asynchronously (with attribution to @Aman9das )

2021-11-23 16:17 UTC, closed without merging