[BUGFIX] slack darkmode not working due to forced bgcolor of elements
getferdi/recipes pull request #770
Opened 2021-11-23 15:30 UTC by jpmschuler

Seems Slack updated there HTML classes, thus `darkmode.css` needs to override new elements.
rels https://github.com/getferdi/ferdi/issues/1914

2021-11-23 16:15 UTC, vraravam requested changes

2021-11-23 16:15 UTC, vraravam commented on recipes/slack/darkmode.css
> -body {
Whenever any file changes in a recipe, there's a validation check wherein the `version` in the `package.json` will also need to be bumped up. Please fix and test this with the command in the `CONTRIBUTING.md` file:
``` pmpn i && pnpm run package`

2021-11-24 19:11 UTC, jpmschuler commented
done. 

FWIW: this bumping should probably be a github action instead in order to have version agnostic PRs.

Nevertheless additionally: the recommit hook throws errors:
```
> eslint . --fix
ferdi/recipes/recipes/toggl/webview-unsafe.js
  2:5   error  'ferdi' is not defined  no-undef
  2:27  error  'ferdi' is not defined  no-undef
  7:9   error  'ferdi' is not defined  no-undef
  9:9   error  'ferdi' is not defined  no-undef
```

2021-11-24 23:13 UTC, vraravam approved these changes
Thanks for the contribution @jpmschuler !

2021-11-24 23:14 UTC, merged

2021-12-23 16:45 UTC, kytwb commented
@all-contributors please add @jpmschuler for code