Added recipe for Circuit
getferdi/recipes pull request #771
Opened 2021-11-24 08:07 UTC by simonszu

I have added a recipe for https://www.circuit.com/ which is a work-related team chat used by some companies in Germany.

2021-11-24 08:54 UTC, vraravam requested changes
There would have been changes to `all.json` when you run the commands as denoted in the `CONTRIBUTING.md` - please run that.

2021-11-24 08:54 UTC, vraravam commented on recipes/circuit/webview.js
> +    Ferdi.setBadge(Number.parseInt(unread, 10));
Lines 10 through 15 can be replaced by `Ferdi.safeParseInt`

2021-11-24 08:54 UTC, vraravam commented on recipes/circuit/webview.js
> +  const loopFunc = () => {
You don't need to wrap 1 function call inside another function call. You can directly call `Ferdi.loop(getMessages);`

2021-11-24 08:58 UTC, simonszu commented on recipes/circuit/webview.js
> +  const loopFunc = () => {
I know. But i wanted to prepare for possible future improvements, and therefore followed the example in the documentation: https://github.com/getferdi/recipes/blob/master/docs/integration.md#webviewjs

2021-11-24 09:02 UTC, simonszu commented
I'm sorry, but there is no CONTRIBUTING.md inside this repo. The documentation for developing new recipes says: 

> Simply copy that whole folder into the repositories "recipes" folder. You'll now need to push your changes to Git and create a Pull Request from your fork repository to our repository using the GitHub website.

2021-11-24 09:07 UTC, vraravam commented
> I'm sorry, but there is no CONTRIBUTING.md inside this repo. The documentation for developing new recipes says:
> 
> > Simply copy that whole folder into the repositories "recipes" folder. You'll now need to push your changes to Git and create a Pull Request from your fork repository to our repository using the GitHub website.

Please see: https://github.com/vraravam/recipes/blob/master/docs/integration.md#create-a-recipe

2021-11-24 09:08 UTC, simonszu commented on recipes/circuit/webview.js
> +    Ferdi.setBadge(Number.parseInt(unread, 10));
Sounds interesting. This method is not documented [here](https://github.com/getferdi/recipes/blob/master/docs/frontend_api.md) which is the designated documentation about the webview.js. Where can i find documentation about `Ferdi.safeParseInt`?

2021-11-24 09:14 UTC, simonszu commented
This documentation about creating a recipe has marked the pnpm steps as optional. I was able to create the folder and the scaffolding manually, and the pnpm scripts only had additional hurdles for me, since they assumed to have ferdi installed on the host they are executed on, which was not the case for me, since i created the recipe on the headless server where ferdi-server is running. 

If these scripts are mandatory for having recipes acceptable for pull requests, please mark them as such.

2021-11-24 09:16 UTC, vraravam commented
> This documentation about creating a recipe has marked the pnpm steps as optional.

Yes, you can use the creation script optionally. But, the verification step is NOT marked as optional - see step 4 in the same link.

2021-11-24 09:21 UTC, vraravam commented
> This documentation about creating a recipe has marked the pnpm steps as optional.

I see your point. But,  as far as the `pre-commit` hook, and the PR's pre-flight checklist - both of them callout that the author should have run `pnpm run package` - which is what I am also asking for

2021-11-24 09:27 UTC, vraravam commented
I have updated the docs with the mandatory step - thanks for pointing it out

2021-11-24 09:28 UTC, simonszu commented
I see. I have now executed the pnpm scripts and noticed that the all.json was changed. Hopefully from a technical perspective this is solved.

2021-11-24 09:31 UTC, vraravam requested changes

2021-11-24 09:31 UTC, vraravam commented on all.json
> -[
This file should not be deleted! The `pnpm` scripts will generate a block of json code into this file (ie edited not deleted)

2021-11-24 09:31 UTC, vraravam commented on recipes/circuit/package.json
> +  "version": "1.0.1",
Since this is the first time this recipe is being created - please start off with `1.0.0` for the version.

2021-11-24 09:31 UTC, vraravam commented on recipes/circuit/webview.js
> +    Ferdi.setBadge(Number.parseInt(unread, 10));
Again, a miss - thanks for surfacing. I will add that in. There seem to be quite a few new APIs that are missing from this documentation. Please see any of the other recipes to understand about `safeParseInt`

2021-11-24 10:03 UTC, simonszu commented on all.json
> -[
I did not delete anything.

2021-11-24 10:06 UTC, simonszu commented on recipes/circuit/package.json
> +  "version": "1.0.1",
I submitted it with 1.0.0 initially. The pnpm create script which i executed afterwards to modify the all.json triggered a linter which changed line 13 in webview.js, and the pre-commit hook to submit the all.json complained afterwards that the webview.js was changed but the version number was not increased, so that's why the recipe is already on 1.0.1

2021-11-24 10:07 UTC, vraravam commented on all.json
> -[
Please resurrect the `all.json` (it appears to be deleted in this commit).

When running the `pnpm run package` command, it will add some more lines into the `all.json` once it finishes successfully. Please add those into the commit/PR

2021-11-24 10:09 UTC, simonszu commented on all.json
> -[
Yeah, i see. Strange that it got removed. Hopefully everything's fine again.

2021-11-24 10:12 UTC, simonszu commented
For what i see, `Ferdi.safeParseInt` is a wrapper for `Number.parseInt` which does some additional steps. I am not sure about the additional steps, and they are not really deferrable from other recipes for me. 

i'm cool with putting this PR on hold until a documentation for `safeParseInt` is available, then i can modify the webview.js as needed, and we can proceed :)

2021-11-24 10:52 UTC, vraravam commented
> i'm cool with putting this PR on hold until a documentation for `safeParseInt` is available

This is now ready. Please rebase from `master` of the parent repo to get all the documentation and other changes.

2021-11-24 11:02 UTC, vraravam requested changes

2021-11-24 11:02 UTC, vraravam commented on recipes/circuit/package.json
> +  "version": "1.0.1",
Yes - this is a catch-22 . For such unique cases - please override both `package.json` and `all.json` with `1.0.0` and commit with `git commit --no-verify`. This will bypass the pre-commit hook.

2021-11-24 11:03 UTC, vraravam commented on recipes/circuit/webview.js
> +    Ferdi.setBadge(Number.parseInt(unread, 10));
this documentation is now updated. thanks once again for bringing this up.

2021-11-24 12:00 UTC, simonszu commented
OK, the version number was forced to `1.0.0`, and i have used `safeParseInt` in the webview.js.

2021-11-24 12:04 UTC, vraravam approved these changes

2021-11-24 12:05 UTC, merged

2021-11-24 12:33 UTC, simonszu commented
Nice. Thank you very much for your patience and support.

2021-12-23 16:44 UTC, kytwb commented
@all-contributors please add @simonszu for code