Add RingCentral recipe
getferdi/recipes pull request #776
Opened 2021-11-28 10:06 UTC by deadmeu

This PR adds a recipe for the RingCentral unified communications app, which is the latest version of their teams messaging product (succeeding their classic messaging product _Glip_).

Both direct and indirect message badges have been implemented. Notifications don't work (I think the cause could be a permission issue) but that is something I'll look at in the future.

I've had a [basic recipe available](https://github.com/deadmeu/ferdi-ringcentral) for a while, but have only just bothered to clean things up to be published now.

This PR may resolve future issues like getferdi/ferdi#1388.

2021-11-28 11:49 UTC, vraravam requested changes

2021-11-28 11:49 UTC, vraravam commented on recipes/proton-mail/webview.js
> +    for (const counterElement of document.querySelectorAll('.navigation-counter-item')) {
Why are you editing the `proton-mail` recipe in this PR?

2021-11-28 11:49 UTC, vraravam commented on recipes/ringcentral/README.md
> +This is a Ferdi recipe for the RingCentral unified communications app (formerly Glip).
a `README.md` is no longer required - please remove

2021-11-28 12:01 UTC, deadmeu commented on recipes/proton-mail/webview.js
> +    for (const counterElement of document.querySelectorAll('.navigation-counter-item')) {
I think it was the pre-commit `eslint . --fix` command that made the change.

2021-11-28 14:57 UTC, vraravam approved these changes

2021-11-28 14:58 UTC, merged

2021-12-23 16:39 UTC, kytwb commented
@all-contributors please add @deadmeu for code