Stop clearing storage data on unload in WhatsApp recipe
getferdi/recipes pull request #778
Opened 2021-11-30 22:57 UTC by ruippeixotog

Clearing all WhatsApp local stores before unloading was added in https://github.com/meetfranz/recipe-whatsapp/commit/047253c402bd9d81f36eb9905b0d4046a67cf14a for reasons unclear. The new [multi-device beta](https://faq.whatsapp.com/general/download-and-installation/about-multi-device-beta/?lang=en) doesn't seem to like this: reloading WhatsApp causes Ferdi to be stuck on a "Connecting..." screen. Keeping local stores fixes this issue with no apparent drawback.

2021-12-01 01:43 UTC, vraravam requested changes
I haven't tested this yet. The code change is ok. But, as part of any changes in recipes, you will need to follow the instructions in the `updating.md` file and add the changes to `package.json` and `all.json`. Please add those before this can be approved.

2021-12-01 09:37 UTC, ruippeixotog commented
Sorry for missing this @vraravam! Done in 045bce3.

2021-12-01 09:45 UTC, vraravam approved these changes

2021-12-01 09:46 UTC, merged

2021-12-23 16:38 UTC, kytwb commented
@all-contributors please add @ruippeixotog for code