Add Iris Messenger recipe
getferdi/recipes pull request #783
Opened 2021-12-03 21:50 UTC by vbuzzano

A recipe for Iris Messenger 
service url: https://iris.to
iris.to github: https://github.com/irislib/iris-messenger

2021-12-03 23:59 UTC, vraravam requested changes
Thanks for the contribution!

2021-12-03 23:59 UTC, vraravam commented on recipes/iris-messenger/index.js
> +module.exports = Ferdi => Ferdi;
As of some commits done yesterday, this file (if empty or with only this "default" export) can be safely deleted.

2021-12-03 23:59 UTC, vraravam commented on recipes/iris-messenger/package.json
> +    "hasTeamId": false
According to [the documentation](https://github.com/vraravam/recipes/blob/master/docs/configuration.md), `hasTeamId` is `false` by default. Please delete this line.

2021-12-04 18:33 UTC, vbuzzano commented on recipes/iris-messenger/package.json
> +    "hasTeamId": false
ah ok.  I thougth it was like Franz. I remember it was true by default.
I change asap :)

2021-12-04 18:42 UTC, vbuzzano commented on recipes/iris-messenger/package.json
> +    "hasTeamId": false
ok i have done the change. don't remember if i need to do re-pull request or something else ?

2021-12-05 00:45 UTC, vraravam requested changes

2021-12-05 00:45 UTC, vraravam commented on recipes/iris-messenger/index.js
> +module.exports = Ferdi => Ferdi;
Please delete this file.

2021-12-05 00:45 UTC, vraravam commented on recipes/iris-messenger/package.json
> +    "hasTeamId": false
no need to recreate the PR. I am reviewing in this PR itself. Tx

2021-12-05 08:14 UTC, vbuzzano commented on recipes/iris-messenger/index.js
> +module.exports = Ferdi => Ferdi;
I think you are wrong. Only empty webview.js files have been removed. And the package.js script still checks if the index.js file exists. Without it, we can't commit because an error is returned.

check: https://github.com/getferdi/recipes/blob/be4c5abcae4ef3d49bec8dba632381989af05311/scripts/package.js#L269-L274

2021-12-05 08:15 UTC, vbuzzano commented on recipes/iris-messenger/index.js
> +module.exports = Ferdi => Ferdi;
should i delete the file and remove package.js check ? or keep index.js in the recipe folder

2021-12-05 09:26 UTC, vraravam commented on recipes/iris-messenger/index.js
> +module.exports = Ferdi => Ferdi;
sorry - yes, my bad. I was thinking this was the `webview.js`

2021-12-05 09:27 UTC, vraravam approved these changes

2021-12-05 09:28 UTC, merged

2021-12-23 16:33 UTC, kytwb commented
@all-contributors please add @vbuzzano for code